package main

type Parser Peg {
    Calc
}

root <- expression EOT /
        expression <.+> {p.Err(begin, buffer)} EOT /
        <.+> {p.Err(begin, buffer)} EOT

EOT <- !.

expression <- additive

additive <- multitive (
    '+' multitive {p.PushOpe("+")} /
    '-' multitive {p.PushOpe("-")} 
)*

multitive <- value (
    '*' '*' value {p.PushOpe("**")} /
    '*' value {p.PushOpe("*")} / 
    '/' value {p.PushOpe("/")} 
)*

value <-
    <[0-9]+> {p.PushDigit(text)} /
    '(' expression ')'
