Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "master" do |host|
    host.vm.box = "ubuntu/bionic64"
    host.vm.hostname = "master"

    host.vm.provider "virtualbox" do |v|
      v.memory = 3072
    end
    host.vm.network "public_network"
    host.vm.network "private_network", ip: "10.0.1.2",
        virtualbox__intnet: "kub-test"
  end

  config.vm.define "worker-1" do |host|
    host.vm.box = "ubuntu/bionic64"
    host.vm.hostname = "worker-1"

    host.vm.network "public_network"
    host.vm.network "private_network", ip: "10.0.1.10",
        virtualbox__intnet: "kub-test"
  end

  config.vm.define "worker-2" do |host|
    host.vm.box = "ubuntu/bionic64"
    host.vm.hostname = "worker-2"

    host.vm.network "public_network"
    host.vm.network "private_network", ip: "10.0.1.11",
        virtualbox__intnet: "kub-test"
  end
end
