@startuml
entity StubResolver
boundary DNSForwarder
entity FullServiceResolver
collections AuthoritativeServers
StubResolver ->o DNSForwarder: query: UDP(53)

DNSForwarder o-> FullServiceResolver: query: UDP(53)
activate FullServiceResolver
FullServiceResolver -> AuthoritativeServers
FullServiceResolver <-- AuthoritativeServers
FullServiceResolver -> AuthoritativeServers
FullServiceResolver <-- AuthoritativeServers
FullServiceResolver -> AuthoritativeServers
FullServiceResolver <-- AuthoritativeServers
FullServiceResolver -> AuthoritativeServers
FullServiceResolver <-- AuthoritativeServers

DNSForwarder o<-- FullServiceResolver
deactivate FullServiceResolver
StubResolver <--o DNSForwarder
@enduml